### ISSUE TITLE
More options for mirrors

### ISSUE THREAD

**Issue by lord2800** [gds-operations/puppet-aptly#35]
I'd like support for the `-with-udebs` and `-with-sources` flags. Support for `-filter` and `-filter-with-deps` would also be nice.

**Comment by antonio** [comment]
`-with-udebs` and `-with-sources` are already supported with parameters. With regards to other parameters and flags, I have a branch that addresses this, but haven't opened a PR since it is disruptive and will break other people's manifests. 

It drops the flags and instead adds a hash parameter in which you can specify any flag or option for `aptly`. I use it to specify the parameters via hiera, like this:

```yml
  ntop-precise-all:
    location: 'http://packages.ntop.org/apt-stable/12.04/'
    key: '7921DF34'
    release: 'precise'
    prefix: 'ntop-precise-all'
    release_path: 'all/'
    mirror_cmd_opts:
      '-with-sources': false
      '-force-components': true
```

If you are interested, you can find it at https://github.com/antonio/puppet-aptly/tree/cmd-options

Also, if any of the maintainers of the project is interested in this as well, I can update my branch to add back the parameters I've delete (`with-sources` and `with-udebs`) and add a deprecation notice to them, and open a PR with my changes.
